"""Install and manage the optional pwdnote Zsh integration."""

from __future__ import annotations

import os
import re
import shlex
from pathlib import Path

from .config import get_config_dir

MANAGED_BLOCK_START = "# >>> pwdnote shell integration >>>"
MANAGED_BLOCK_END = "# <<< pwdnote shell integration <<<"
_MANAGED_BLOCK_RE = re.compile(
    rf"^{re.escape(MANAGED_BLOCK_START)}\n.*?^{re.escape(MANAGED_BLOCK_END)}\n?",
    re.MULTILINE | re.DOTALL,
)

ZSH_INTEGRATION = """\
# Generated by pwdnote. Do not edit directly.
# Run `pwdnote shell install` to refresh this file.
pwdnote() {
    local subcommand="${1-}"

    if [[ "$subcommand" == "paste" || "$subcommand" == "p" ]]; then
        if [[ "${2-}" == "--help" ]]; then
            command pwdnote "$@"
            return $?
        fi

        shift

        local item
        item="$(command pwdnote cat "$@")" || return $?

        print -z -- "$item"
        return 0
    fi

    command pwdnote "$@"
}
"""


def get_integration_path() -> Path:
    """Return the generated Zsh integration path."""
    return (get_config_dir() / "shell" / "pwdnote.zsh").expanduser().resolve()


def get_zshrc_path() -> Path:
    """Return the Zsh startup file managed by pwdnote."""
    return (Path.home() / ".zshrc").resolve()


def render_zsh_integration() -> str:
    """Return the canonical Zsh wrapper function."""
    return ZSH_INTEGRATION


def render_managed_block(integration_path: Path | None = None) -> str:
    """Return the managed .zshrc source block."""
    path = integration_path or get_integration_path()
    return (
        f"{MANAGED_BLOCK_START}\n"
        f"source {shlex.quote(str(path))}\n"
        f"{MANAGED_BLOCK_END}\n"
    )


def _remove_managed_blocks(content: str) -> tuple[str, bool]:
    updated, count = _MANAGED_BLOCK_RE.subn("", content)
    return updated, count > 0


def install() -> tuple[Path, Path]:
    """Install or refresh the integration file and managed .zshrc block."""
    integration_path = get_integration_path()
    integration_path.parent.mkdir(parents=True, exist_ok=True)
    integration_path.write_text(render_zsh_integration(), encoding="utf-8")
    try:
        os.chmod(integration_path, 0o600)
    except OSError:
        pass

    zshrc_path = get_zshrc_path()
    zshrc_path.parent.mkdir(parents=True, exist_ok=True)
    existing = zshrc_path.read_text(encoding="utf-8") if zshrc_path.exists() else ""
    unmanaged, _ = _remove_managed_blocks(existing)
    separator = "" if not unmanaged or unmanaged.endswith("\n") else "\n"
    zshrc_path.write_text(
        unmanaged + separator + render_managed_block(integration_path),
        encoding="utf-8",
    )
    return integration_path, zshrc_path


def is_installed() -> bool:
    """Return whether both canonical integration pieces are installed once."""
    integration_path = get_integration_path()
    zshrc_path = get_zshrc_path()
    if not integration_path.is_file() or not zshrc_path.is_file():
        return False
    try:
        if integration_path.read_text(encoding="utf-8") != render_zsh_integration():
            return False
        zshrc = zshrc_path.read_text(encoding="utf-8")
    except OSError:
        return False
    blocks = _MANAGED_BLOCK_RE.findall(zshrc)
    return len(blocks) == 1 and blocks[0] == render_managed_block(integration_path)


def uninstall() -> tuple[bool, Path]:
    """Remove only the generated file and managed .zshrc block."""
    integration_path = get_integration_path()
    zshrc_path = get_zshrc_path()
    changed = False

    if zshrc_path.is_file():
        existing = zshrc_path.read_text(encoding="utf-8")
        updated, removed = _remove_managed_blocks(existing)
        if removed:
            zshrc_path.write_text(updated, encoding="utf-8")
            changed = True

    if integration_path.exists():
        integration_path.unlink()
        changed = True

    try:
        integration_path.parent.rmdir()
    except OSError:
        pass

    return changed, zshrc_path
