"""Install and manage the optional cross-platform Zsh integration."""

from __future__ import annotations

import os
import re
import shlex
from dataclasses import dataclass
from pathlib import Path

from .config import get_config_dir

ACCEPTED_SHELLS = {"zsh", "bash", "fish", "powershell", "pwsh"}
SHELL_DISPLAY_NAMES = {
    "zsh": "Zsh",
    "bash": "Bash",
    "fish": "Fish",
    "powershell": "PowerShell",
    "pwsh": "PowerShell",
}

MANAGED_BLOCK_START = "# >>> pwdnote zsh integration >>>"
MANAGED_BLOCK_END = "# <<< pwdnote zsh integration <<<"
_LEGACY_BLOCK_START = "# >>> pwdnote shell integration >>>"
_LEGACY_BLOCK_END = "# <<< pwdnote shell integration <<<"
_MANAGED_BLOCK_RE = re.compile(
    rf"^{re.escape(MANAGED_BLOCK_START)}\n.*?^{re.escape(MANAGED_BLOCK_END)}\n?",
    re.MULTILINE | re.DOTALL,
)
_LEGACY_BLOCK_RE = re.compile(
    rf"^{re.escape(_LEGACY_BLOCK_START)}\n.*?^{re.escape(_LEGACY_BLOCK_END)}\n?",
    re.MULTILINE | re.DOTALL,
)

ZSH_INTEGRATION = """\
# Generated by pwdnote. Do not edit directly.
# Run `pwdnote shell install zsh` to refresh this file.
pwdnote() {
    local subcommand="${1-}"

    if [[ "$subcommand" == "paste" || "$subcommand" == "p" ]]; then
        if [[ "${2-}" == "--help" ]]; then
            command pwdnote "$@"
            return $?
        fi

        shift

        local item
        item="$(command pwdnote cat "$@")" || return $?

        print -z -- "$item"
        return 0
    fi

    command pwdnote "$@"
}
"""


@dataclass(frozen=True)
class ZshIntegrationStatus:
    """Status of the generated file and managed .zshrc source block."""

    integration_file_present: bool
    integration_file_current: bool
    source_block_present: bool
    source_block_current: bool

    @property
    def complete(self) -> bool:
        return self.integration_file_current and self.source_block_current


def normalize_shell(value: str | None) -> str | None:
    """Normalize accepted shell names and executable paths."""
    if value is None:
        return None
    name = value.strip().replace("\\", "/").rsplit("/", 1)[-1].lower()
    if name.endswith(".exe"):
        name = name[:-4]
    return name if name in ACCEPTED_SHELLS else None


def detect_shell() -> str | None:
    """Conservatively detect the configured login shell from ``$SHELL``."""
    return normalize_shell(os.environ.get("SHELL"))


def shell_display_name(shell: str) -> str:
    """Return a stable display name for a normalized shell."""
    return SHELL_DISPLAY_NAMES[shell]


def get_integration_path() -> Path:
    """Return the generated Zsh integration path."""
    return (get_config_dir() / "shell" / "pwdnote.zsh").expanduser().resolve()


def get_zshrc_path() -> Path:
    """Return the Zsh startup file managed by pwdnote."""
    return (Path.home() / ".zshrc").resolve()


def render_zsh_integration() -> str:
    """Return the canonical Zsh wrapper function."""
    return ZSH_INTEGRATION


def render_managed_block(integration_path: Path | None = None) -> str:
    """Return the managed .zshrc source block."""
    path = integration_path or get_integration_path()
    return (
        f"{MANAGED_BLOCK_START}\n"
        f"source {shlex.quote(str(path))}\n"
        f"{MANAGED_BLOCK_END}\n"
    )


def render_source_command(zshrc_path: Path | None = None) -> str:
    """Return a safely quoted command for reloading .zshrc."""
    path = zshrc_path or get_zshrc_path()
    return f"source {shlex.quote(str(path))}"


def _remove_managed_blocks(content: str) -> tuple[str, bool]:
    updated, current_count = _MANAGED_BLOCK_RE.subn("", content)
    updated, legacy_count = _LEGACY_BLOCK_RE.subn("", updated)
    return updated, current_count + legacy_count > 0


def install() -> tuple[Path, Path]:
    """Install or refresh the integration file and managed .zshrc block."""
    integration_path = get_integration_path()
    integration_path.parent.mkdir(parents=True, exist_ok=True)
    integration_path.write_text(render_zsh_integration(), encoding="utf-8")
    try:
        os.chmod(integration_path, 0o600)
    except OSError:
        pass

    zshrc_path = get_zshrc_path()
    zshrc_path.parent.mkdir(parents=True, exist_ok=True)
    existing = zshrc_path.read_text(encoding="utf-8") if zshrc_path.exists() else ""
    unmanaged, _ = _remove_managed_blocks(existing)
    separator = "" if not unmanaged or unmanaged.endswith("\n") else "\n"
    zshrc_path.write_text(
        unmanaged + separator + render_managed_block(integration_path),
        encoding="utf-8",
    )
    return integration_path, zshrc_path


def get_status() -> ZshIntegrationStatus:
    """Inspect the generated file and managed block without modifying them."""
    integration_path = get_integration_path()
    zshrc_path = get_zshrc_path()
    file_present = integration_path.is_file()
    file_current = False
    block_present = False
    block_current = False

    try:
        if file_present:
            file_current = (
                integration_path.read_text(encoding="utf-8")
                == render_zsh_integration()
            )
        if zshrc_path.is_file():
            zshrc = zshrc_path.read_text(encoding="utf-8")
            current_blocks = _MANAGED_BLOCK_RE.findall(zshrc)
            legacy_blocks = _LEGACY_BLOCK_RE.findall(zshrc)
            block_present = bool(current_blocks or legacy_blocks)
            block_current = (
                len(current_blocks) == 1
                and not legacy_blocks
                and current_blocks[0] == render_managed_block(integration_path)
            )
    except (OSError, UnicodeError):
        pass

    return ZshIntegrationStatus(
        integration_file_present=file_present,
        integration_file_current=file_current,
        source_block_present=block_present,
        source_block_current=block_current,
    )


def is_installed() -> bool:
    """Return whether both canonical integration pieces are installed once."""
    return get_status().complete


def uninstall() -> tuple[bool, Path]:
    """Remove only the generated file and managed .zshrc block."""
    integration_path = get_integration_path()
    zshrc_path = get_zshrc_path()
    changed = False

    if zshrc_path.is_file():
        existing = zshrc_path.read_text(encoding="utf-8")
        updated, removed = _remove_managed_blocks(existing)
        if removed:
            zshrc_path.write_text(updated, encoding="utf-8")
            changed = True

    if integration_path.exists():
        integration_path.unlink()
        changed = True

    try:
        integration_path.parent.rmdir()
    except OSError:
        pass

    return changed, zshrc_path
